### PR TITLE
Updated main.py

### PR DESCRIPTION
**Pull request by loya7189**
Added a working trip_edit route

### CODE REVIEW

**Comment by loya7189** [comment]
Updated main.py by adding a trip edit enpoint, and updating the trip_view HTML file respectively. Clicking the edit button is not broken anymore and allows for a name change of the trip.

**Comment by ernielum** [comment]
Javascript functions should be moved to script.js for consistency and organization

**Comment by ernielum** [comment]
Your main.py file still contains obsolete routes and dummy FE data that is no longer needed

**Comment by loya7189** [comment]
Moved js functions. To scrips.js. Also, I'm not sure what dummy data you're talking about, this branch is from the most recent version of main. Can you remove whatever it is that you mean?

**Comment by ernielum** [comment]
cannot do this pull request because it looks like you only requested Michelle to do it. There are a lot of obsolete endpoints and dummy data in main.py that I can fix once this pull request goes through.

**Review by michelle915 — APPROVED** [review]

**Pull request merged**
